import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/shared/header/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className="antialiased"
				style={{
					fontFamily:
						'"Hiragino Kaku Gothic ProN", "ヒラギノ角ゴ ProN W3", "Hiragino Kaku Gothic Pro", "ヒラギノ角ゴ Pro W3", "メイリオ", Meiryo, "游ゴシック", YuGothic, sans-serif',
				}}
			>
				<Header />
				<div className="flex min-h-screen w-full justify-center px-6 md:px-0">
					<div className="w-full max-w-7xl">{children}</div>
				</div>
			</body>
		</html>
	);
}
